# Generated by Django 3.2.5 on 2022-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_package_name_details_pkg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='content',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_name',
            field=models.CharField(max_length=124),
        ),
    ]
