# Generated by Django 3.2.5 on 2022-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220726_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_label', models.CharField(max_length=124)),
                ('Carousel_content', models.TextField()),
                ('Carousel_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
