# Generated by Django 3.2.5 on 2022-08-17 10:51

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_carousels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousels',
            old_name='Carousel_content',
            new_name='carousel_content',
        ),
        migrations.RenameField(
            model_name='carousels',
            old_name='Carousel_img',
            new_name='carousel_img',
        ),
        migrations.AddField(
            model_name='carousels',
            name='carousel_video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
