# Generated by Django 3.2.5 on 2022-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220817_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousels',
            name='carousel_video',
            field=models.FileField(upload_to=''),
        ),
    ]
