# Generated by Django 3.2.5 on 2022-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_carousels_carousel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousels',
            name='carousel_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
