# Generated by Django 3.2.5 on 2022-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_carousels_carousel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousels',
            name='carousel_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carousels',
            name='carousel_label',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='carousels',
            name='carousel_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
