# Generated by Django 3.2.5 on 2022-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220817_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('media_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
