# Generated by Django 3.2.5 on 2022-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_media_media_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_label', models.CharField(blank=True, max_length=124, null=True)),
                ('article_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
