# Generated by Django 3.2.5 on 2022-09-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi_name', models.CharField(blank=True, max_length=124, null=True)),
                ('hi_nameAR', models.CharField(blank=True, max_length=124, null=True)),
                ('hi_logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
