# Generated by Django 3.2.5 on 2022-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_healthinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousels',
            name='carousel_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousels',
            name='carousel_label_ar',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
