# Generated by Django 3.2.5 on 2022-09-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220915_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='details_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_name_ar',
            field=models.CharField(default=1, max_length=124),
            preserve_default=False,
        ),
    ]
